In [82]:
import pandas as pd
import numpy as np

In [83]:
df = pd.DataFrame({'A': [1, 2, 3], 'B': [4, 5, 6]})

df_copy = df.copy()

df['A'] = [10, 20, 30]

In [84]:
print(df)

    A  B
0  10  4
1  20  5
2  30  6


In [85]:
print(df_copy)

   A  B
0  1  4
1  2  5
2  3  6


In [ ]:
df['A'] = df['A'].astype(str)

df['C'] = df['A'] + '99'

print(df)

In [ ]:
df1 = pd.DataFrame({'A': [1, 2, 3], 'B': [4, 5, 6]})
df2 = pd.DataFrame({'A': [10, 20, 30], 'B': [40, 50, 60]})

df_concatenado = pd.concat([df1, df2], ignore_index=True)

print(df_concatenado)

    A   B
0   1   4
1   2   5
2   3   6
3  10  40
4  20  50
5  30  60


In [88]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

c = np.concatenate((a, b))

print(c)

[1 2 3 4 5 6]


In [94]:
a = np.array([[1, 2, 3, 4, 5, 6], [7, 8, 9, 10, 11, 12]])
b = np.array([[10, 20, 30, 40, 50, 60], [70, 80, 90, 100, 110, 120]])

c = np.concatenate((a, b), axis=1)

print(c)

[[  1   2   3   4   5   6  10  20  30  40  50  60]
 [  7   8   9  10  11  12  70  80  90 100 110 120]]
