In [138]:
lista = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
print(lista[0:5])

[0, 1, 2, 3, 4]


In [139]:
string = 'Python'
print(string[1:4])

yth


In [140]:
import numpy as np

In [141]:
array = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print(array[0:5])

[0 1 2 3 4]


In [142]:
print(array[1:4])

[1 2 3]


In [143]:
import pandas as pd

In [144]:
s = pd.Series([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print(s[0:5])

0    0
1    1
2    2
3    3
4    4
dtype: int64


In [145]:
s = pd.Series([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print(s[1:4])

1    1
2    2
3    3
dtype: int64


In [146]:
df = pd.DataFrame(
    {
        'A': [0, 1, 2, 3, 4],
        'B': [5, 6, 7, 8, 9]
    }
)

print(df[1:4])

   A  B
1  1  6
2  2  7
3  3  8


In [147]:
print(lista[::2])

[0, 2, 4, 6, 8]


In [148]:
print(lista[::-1])

[9, 8, 7, 6, 5, 4, 3, 2, 1, 0]


In [149]:
print(array[array > 2])

[3 4 5 6 7 8 9]


In [150]:
random = np.random.randn(10)
print(random)

[-0.11472449 -0.14180997 -0.12909707 -0.18013993 -0.76542711  0.9508509
 -1.10825951  0.7887819   0.21138983 -0.59065328]


In [151]:
pd.Series(random)

0   -0.114724
1   -0.141810
2   -0.129097
3   -0.180140
4   -0.765427
5    0.950851
6   -1.108260
7    0.788782
8    0.211390
9   -0.590653
dtype: float64